updating job notification

diff --git a/.github/workflows/python-unit-tests-release.yml b/.github/workflows/python-unit-tests-release.yml
--- a/.github/workflows/python-unit-tests-release.yml
+++ b/.github/workflows/python-unit-tests-release.yml
@@ -21,7 +21,7 @@ jobs:
           echo "Matrix: $FOLDERS"
           echo "::set-output name=matrix::$FOLDERS"
 
-  run-unit-tests-matrix:
+  run-unit-tests-release:
     needs: prepare-matrix
     strategy:
       fail-fast: false
@@ -52,8 +52,53 @@ jobs:
         run: |
           pytest tests/unit/${{ matrix.folder }}
 
+  run-unit-tests-release-success:
+    needs: run-unit-tests-release
+    runs-on: ubuntu-latest
+    steps:
+      - name: Notify on failure
+        run: |
+          if [ ${{ job.status }} == 'failure' ]; then
+            echo "Unit tests failed"
+            exit 1
+          else
+            echo "Unit tests passed"
+          fi
+
+  test-build-settings-matrix:
+    needs: run-unit-tests-release
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        os: [ubuntu-latest]
+        python-version: ["3.8", "3.9", "3.10", "3.11"]
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Create and activate virtual environment
+        run: |
+          python -m venv venv
+          source venv/bin/activate
+
       - name: Test build settings
         run: |
-          pip uninstall -y macrosynergy
-          pip install .[all] 
+          pip install .[all]
           python -c "import macrosynergy; print(macrosynergy.__version__)"
+
+  test-build-settings-matrix-success:
+    needs: test-build-settings-matrix
+    runs-on: ubuntu-latest
+    steps:
+      - name: Notify on failure
+        run: |
+          if [ ${{ job.status }} == 'failure' ]; then
+            echo "Build settings test failed"
+            exit 1
+          else
+            echo "Build settings test passed"
+          fi
diff --git a/.github/workflows/python-unit-tests.yml b/.github/workflows/python-unit-tests.yml
--- a/.github/workflows/python-unit-tests.yml
+++ b/.github/workflows/python-unit-tests.yml
@@ -54,7 +54,12 @@ jobs:
   run-unit-tests-success:
     needs: run-unit-tests
     runs-on: ubuntu-latest
-    if: ${{ always() }}
     steps:
-      - name: Print success message
-        run: echo "Unit tests passed successfully!"
+      - name: Notify on Failure
+        run: |
+          if [ ${{ job.status }} == 'failure' ]; then
+            echo "Unit tests failed"
+            exit 1
+          else
+            echo "Unit tests passed"
+          fi
